In [24]:
import pandas as pd
import numpy as np
from sklearn.decomposition import NMF
import pickle

In [3]:
df_words = pd.read_csv('aplicacao_modelagem_topicos/data/df_words_tfidf.csv')
df_words.head()

,aaa,aaap,aalen,aalt,aaltouniversityac,aand,aap,aarhu,aaron,ab,...,zui,zul,zumb,zumbif,zumbific,zumvel,zurbuchen,zuriqu,zwicky,zykov
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.015552,0.035184,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.029805,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0

In [27]:
df_gizmodo = pd.read_csv('aplicacao_modelagem_topicos/data/noticias_gizmodo.csv')

In [8]:
with open('aplicacao_modelagem_topicos/tfidf_vectorizer', 'rb') as f:
    vectorizer = pickle.load(f)

In [12]:
print(vectorizer.get_feature_names()[:10])

['aaa', 'aaap', 'aalen', 'aalt', 'aaltouniversityac', 'aand', 'aap', 'aarhu', 'aaron', 'ab']

In [14]:
nmf_model = NMF(n_components=6).fit(df_words)

In [15]:
nmf_W = nmf_model.transform(df_words)
nmf_H = nmf_model.components_

In [16]:
print('Matriz W:', nmf_W.shape)
print('Matriz H:', nmf_H.shape)

Matriz W: (1988, 6)
Matriz H: (6, 22298)

In [25]:
# Função para exibir os tópicos
def exibe_topicos(H, W, feature_names, documents, num_top_words, num_top_documents):
    for topic_idx, topic in enumerate(H):
        print('\nTópico %d' % (topic_idx + 1))

        print('   Principais termos: ' + ', '.join([feature_names[i] + ' (%s)' % round(H[topic_idx][i], 2) 
                            for i in topic.argsort()[:-num_top_words - 1:-1]]))       

        # Top documentos relacionados
        print('   Principais notícias relacionadas ao tópico:')

        top_doc_indices = np.argsort( W[:,topic_idx] )[::-1][0:num_top_documents]
        for doc_index in top_doc_indices:

            # Id do documento
            id_doc = int()            
            
            # Texto
            texto = documents.iloc[doc_index]['titulo']
            print('\t-', texto, ' (%s)' % round(W[doc_index][topic_idx], 2))

In [28]:
# Número de palavras mais relacionadas que serão exibidas para cada tópico
num_top_words = 5

# Número de documentos por tópico
num_top_documents = 3

exibe_topicos(nmf_H, nmf_W, vectorizer.get_feature_names(), df_gizmodo , num_top_words, num_top_documents)

Tópico 1
   Principais termos: pod (0.46), pesquis (0.43), estud (0.39), diss (0.32), us (0.31)
   Principais notícias relacionadas ao tópico:
	- Telescópio Kepler enfim dá adeus, depois de mais de nove anos de missão  (0.11)
	- Quando os robôs irão merecer direitos humanos?  (0.11)
	- Novo relatório do Congresso dos EUA pede que NASA intensifique a busca por exoplanetas e alienígenas  (0.1)

Tópico 2
   Principais termos: facebook (1.66), dad (0.43), usuari (0.43), red (0.38), zuckerberg (0.29)
   Principais notícias relacionadas ao tópico:
	- A mais recente falha de segurança do Facebook foi a gota d’água para mim  (0.3)
	- O Facebook atualizou seus termos de serviço e política de dados, mas eles ainda não são claros o bastante  (0.3)
	- Uma lista de todo mundo que está pistola com o Facebook  (0.29)

Tópico 3
   Principais termos: appl (1.52), iphon (1.31), xs (0.44), nov (0.29), ipad (0.29)
   Principais notícias relacionadas ao tópico:
	- Novos iPhones e um novo Apple Watch: tudo que a Apple lançou nesta quarta-feira  (0.32)
	- O que nós achamos que sabemos sobre o novo iPhone  (0.28)
	- O que esperar do evento que anunciará novos iPhones nesta semana  (0.28)

Tópico 4
   Principais termos: download (0.94), app (0.85), gratil (0.78), aplic (0.46), android (0.31)
   Principais notícias relacionadas ao tópico:
	- Os melhores apps da semana para Android  (0.29)
	- Os melhores apps da semana para Android  (0.28)
	- Os melhores apps da semana para Android  (0.28)

Tópico 5
   Principais termos: ub (1.33), motor (0.71), carr (0.36), passag (0.33), auton (0.24)
   Principais notícias relacionadas ao tópico:
	- Uber anuncia funcionalidades de segurança nos EUA que deveriam estar disponíveis há muito tempo  (0.37)
	- Uber irá avisar motorista qual a forma de pagamento da corrida  (0.37)
	- Os planos do Uber para facilitar que o passageiro encontre o motorista  (0.36)

Tópico 6
   Principais termos: googl (0.96), samsung (0.41), pixel (0.38), android (0.36), cam (0.35)
   Principais notícias relacionadas ao tópico:
	- O que esperar do Google I/O 2018  (0.28)
	- [Review] Google Pixel 3: um outro jeito de fazer um baita smartphone  (0.28)
	- Quais produtos esperar do evento de lançamento do Google Pixel 3  (0.27)